#include "hamming.h"

#include <stdint.h>

// Description:
// Encodes a 4-bit message into a Hamming(8, 4) code.
//
// Parameters:
// uint8_t msg - The message to encode.
//
// Returns:
// uint8_t - The Hamming(8, 4) code.
uint8_t ham_encode( uint8_t msg ) {
	static const uint8_t encode_lookup[ 16 ] = { 0, 225, 210, 51, 180, 85, 102, 135, 120, 153, 170, 75, 204, 45, 30, 255 };

	return encode_lookup[ msg & 0xF ];
}

// Description:
// Decodes a Hamming(8, 4) code to a 4-bit message.
//
// Parameters:
// uint8_t code - The Hamming(8, 4) code.
// uint8_t *msg - Where to put the decoded message. Will be unmodified upon failure.
//
// Returns:
// HAM_STATUS - Whether the hamming code could be successfully decoded.
HAM_STATUS ham_decode( uint8_t code, uint8_t *msg ) {
	static const int8_t correctness[ 256 ] = { HAM_OK, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_CORRECT,
		HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_OK,
		HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_OK, HAM_ERR, HAM_CORRECT,
		HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_OK, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_CORRECT,
		HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_OK, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_CORRECT,
		HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_OK, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_CORRECT,
		HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_OK, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_ERR,
		HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_OK, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_CORRECT,
		HAM_CORRECT, HAM_OK, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_ERR,
		HAM_CORRECT, HAM_CORRECT, HAM_OK, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT,
		HAM_CORRECT, HAM_ERR, HAM_OK, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_OK, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_ERR,
		HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR,
		HAM_ERR, HAM_CORRECT, HAM_OK, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_OK, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_CORRECT,
		HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_OK, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR,
		HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_CORRECT, HAM_ERR, HAM_ERR, HAM_CORRECT, HAM_ERR,
		HAM_CORRECT, HAM_CORRECT, HAM_OK };

	static const uint8_t decode_lookup[ 256 ] = { 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 11, 0, 13, 14, 0, 0, 0, 0, 3, 0, 5, 14, 0, 0, 9, 14, 0, 14, 0, 14, 14, 0, 0, 0, 3, 0, 13, 6, 0, 0, 13, 10, 0, 13, 13,
		0, 13, 0, 3, 3, 3, 4, 0, 0, 3, 8, 0, 0, 3, 0, 13, 14, 0, 0, 0, 0, 11, 0, 5, 6, 0, 0, 11, 11, 11, 12, 0, 0, 11, 0, 5, 2, 0, 5, 5, 0, 5, 8, 0, 0, 11, 0, 5, 14, 0, 0, 1, 6, 0, 6, 0, 6, 6, 8, 0,
		0, 11, 0, 13, 6, 0, 8, 0, 0, 3, 0, 5, 6, 0, 8, 8, 8, 0, 8, 0, 0, 15, 0, 0, 0, 7, 0, 7, 7, 7, 0, 9, 10, 0, 12, 0, 0, 7, 0, 9, 2, 0, 4, 0, 0, 7, 9, 9, 0, 9, 0, 9, 14, 0, 0, 1, 10, 0, 4, 0, 0, 7,
		10, 0, 10, 10, 0, 13, 10, 0, 4, 0, 0, 3, 4, 4, 4, 0, 0, 9, 10, 0, 4, 0, 0, 15, 0, 1, 2, 0, 12, 0, 0, 7, 12, 0, 0, 11, 12, 12, 12, 0, 2, 0, 2, 2, 0, 5, 2, 0, 0, 9, 2, 0, 12, 0, 0, 15, 1, 1, 0,
		1, 0, 1, 6, 0, 0, 1, 10, 0, 12, 0, 0, 15, 0, 1, 2, 0, 4, 0, 0, 15, 8, 0, 0, 15, 0, 15, 15, 15 };

	if ( correctness[ code ] != HAM_ERR ) {
		*msg = decode_lookup[ code ];
	}

	return correctness[ code ];
}
